version: '3'
services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: './myapp'
        target: '/myapp'
    ports:
      - '3000:3000'
